name: to_do_list
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv:
  
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.5.0
  uuid: ^3.0.6
  get: ^4.6.6
  auto_size_text: ^3.0.0
  table_calendar: ^3.2.0
  icons_plus: ^4.0.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.15
  shared_preferences: ^2.1.0
  csv: ^5.0.2
  intl: ^0.20.2
  provider: ^6.1.4
  http: ^1.3.0
  flutter_local_notifications: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - data/tasks_data.json
    - data/categories.json 
    - data/